version: "3.8"
services:
  mongodb:
    image: "mongo:4.4.22"
    volumes:
      - mongo_volume:/data/db
    env_file:
      - ./env/project.env
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - backend_logs:/app/logs 
      - ./backend/:/app/ 
      - /app/node_modules
    env_file:
      - ./env/project.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src/:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  mongo_volume:
  backend_logs:
